services:
  phpdev:
    build:
      context: ./php
      dockerfile: ./Dockerfile_dev
      args:
        gitUserName: "$git_user_name"
        gitUserEmail: "$git_user_email"
    ports:
      - 4433:443
      - 8080:80
    volumes:
      - ./../:/var/www/html/
